import jinja2

def generate_main_cpp(num_features: int, num_classes: int, sensor_channels: int) -> str:
    template = """// Auto-generated by Infera ML Engine
// Auto-generated by Infera ML Engine
#include <Arduino.h>
#include "model.h"
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "tensorflow/lite/version.h"

// Constants
constexpr int NUM_FEATURES = {{ num_features }};
constexpr int NUM_CLASSES = {{ num_classes }};
constexpr int SENSOR_CHANNELS = {{ sensor_channels }};

// Tensor Arena
constexpr int kTensorArenaSize = 32 * 1024;
alignas(16) uint8_t tensor_arena[kTensorArenaSize];

// Forward declaration of feature extraction
void extract_time_series_features(float* input_window, int window_length, int channels, float* output_features);

tflite::ErrorReporter* error_reporter = nullptr;
const tflite::Model* model = nullptr;
tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* input = nullptr;
TfLiteTensor* output = nullptr;

void setup() {
    Serial.begin(115200);
    while (!Serial);
    Serial.println("Infera TinyML Model Initialized");

    static tflite::MicroErrorReporter micro_error_reporter;
    error_reporter = &micro_error_reporter;

    model = tflite::GetModel(g_model);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        TF_LITE_REPORT_ERROR(error_reporter, "Model provided is schema version %d not equal to supported version %d.", model->version(), TFLITE_SCHEMA_VERSION);
        return;
    }

    static tflite::AllOpsResolver resolver;
    static tflite::MicroInterpreter static_interpreter(model, resolver, tensor_arena, kTensorArenaSize, error_reporter);
    interpreter = &static_interpreter;

    TfLiteStatus allocate_status = interpreter->AllocateTensors();
    if (allocate_status != kTfLiteOk) {
        TF_LITE_REPORT_ERROR(error_reporter, "AllocateTensors() failed");
        return;
    }

    input = interpreter->input(0);
    output = interpreter->output(0);
}

void loop() {
    // Example inference loop
    // 1. Gather sensor data into window
    // 2. extract_time_series_features(...)
    // 3. Copy features to input->data.f or input->data.int8 (depending on quantization)
    // 4. if (interpreter->Invoke() != kTfLiteOk) { ... }
    // 5. Read output->data.f or output->data.int8
    
    delay(100);
}
"""
    env = jinja2.Environment()
    t = env.from_string(template)
    return t.render(
        num_features=num_features,
        num_classes=num_classes,
        sensor_channels=sensor_channels
    )
