def generate_model_header(tflite_model_content: bytes, variable_name: str = "g_model") -> str:
    """
    Converts a TFLite model binary into a C header file array.
    """
    hex_array = []
    for i, byte in enumerate(tflite_model_content):
        hex_array.append(f"0x{byte:02x}")
    
    # Format array into 12 columns for readability
    formatted_array = ""
    for i in range(0, len(hex_array), 12):
        formatted_array += "    " + ", ".join(hex_array[i:i+12]) + ",\n"
        
    length = len(tflite_model_content)
    
    header_template = f"""// Auto-generated by Infera ML Engine
#ifndef {variable_name.upper()}_H_
#define {variable_name.upper()}_H_

// Model size: {length} bytes
extern const unsigned char {variable_name}[];
extern const int {variable_name}_len;

#endif // {variable_name.upper()}_H_
"""

    source_template = f"""// Auto-generated by Infera ML Engine
#include "{variable_name}.h"

// Align to 16 bytes for optimal performance on 32-bit MCUs
alignas(16) const unsigned char {variable_name}[] = {{
{formatted_array}
}};

const int {variable_name}_len = {length};
"""

    return header_template, source_template
